version: '3.8'

services:
  pycuvslam_ros2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.x86_64
    image: pycuvslam_ros2:x86_64
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../ros2_ws:/workspace/ros2_ws
      - ../config:/workspace/config
    network_mode: host
    stdin_open: true
    tty: true
    command: bash
